#
# MODULE BasicFile for 'ModuleOther'
#
# Generated by: Imraan Iotana
#
# Generated on: 09-12-2025
#


####################################################################################################
<#
.SYNOPSIS
    This function deploys a file, into a folder on the local system, for example C:\Program Files.
.DESCRIPTION
    This function is part of the Universal Deployment Script. It contains functions or variables, that are in other files.
.EXAMPLE
    Start-BasicFileDeployment -DeploymentObject $MyObject -Action 'Install'
.INPUTS
    [PSCustomObject]
    [System.String]
.OUTPUTS
    [System.Boolean]
.NOTES
    Version         : 5.5.3
    Author          : Imraan Iotana
    Creation Date   : November 2025
    Last Update     : November 2025
.COPYRIGHT
    Copyright (C) Iotana. All rights reserved.
#>
####################################################################################################

function Start-BasicFileDeployment {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true,HelpMessage='The object containing the needed information')]
        [PSCustomObject]
        $DeploymentObject,

        [Parameter(Mandatory=$false,HelpMessage='The action that will be performed')]
        [ValidateSet('Install','Uninstall','Reinstall')]
        [System.String]
        $Action = 'Install'
    )

    begin {
        ####################################################################################################
        ### MAIN PROPERTIES ###

        # Output
        [System.Boolean]$DeploymentSuccess  = $null

        ####################################################################################################
    }
    
    process {
        # VALIDATION
        # Validate the FileToCopy
        if (Test-String -IsEmpty $DeploymentObject.FileToCopy) { Write-Line "The FileToCopy string is empty." -Type Fail ; Write-Line -Type ValidationFail ; Return }
        [System.String]$FileToCopyPath = Get-SourceItemPath -FileName $DeploymentObject.FileToCopy
        if (-Not($FileToCopyPath)) { Write-Line -Type ValidationFail ; Return }

        # Validate the DestinationFolder
        if (Test-String -IsEmpty $DeploymentObject.DestinationFolder) { Write-Line "The DestinationFolder string is empty." -Type Fail ; Write-Line -Type ValidationFail ; Return }

        # Write the message
        Write-Line -Type ValidationSuccess

        # EXECUTION
        # Execute the deployment
        try {
            $DeploymentSuccess = switch ($Action) {
                'Install'   {
                    Install-BasicFile -Path $FileToCopyPath -DestinationFolder $DeploymentObject.DestinationFolder -OverwriteExistingFile $DeploymentObject.OverwriteExistingFile
                }
                'Uninstall' {
                    Uninstall-BasicFile -Path $FileToCopyPath -DestinationFolder $DeploymentObject.DestinationFolder -RemoveDuringUninstall $DeploymentObject.RemoveDuringUninstall
                }
            }
        }
        catch {
            Write-FullError
        }

        ####################################################################################################
    }
    
    end {
        # Return the output
        $DeploymentSuccess
    }
}

### END OF SCRIPT
####################################################################################################


####################################################################################################
<#
.SYNOPSIS
    This function installs a file, in a folder on the local system, for example C:\ProgramData
.DESCRIPTION
    This function is part of the Universal Deployment Script. It contains functions or variables, that are in other files.
.EXAMPLE
    Install-BasicFile -Path 'C:\Demo\MyConfigurationFile.xml' -DestinationFolder 'C:\ProgramData\MyApplication'
.INPUTS
    [System.String]
.OUTPUTS
    [System.Boolean]
.NOTES
    Version         : 5.5.3
    Author          : Imraan Iotana
    Creation Date   : November 2025
    Last Update     : November 2025
.COPYRIGHT
    Copyright (C) Iotana. All rights reserved.
#>
####################################################################################################

function Install-BasicFile {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true,HelpMessage='The path of the file that will be copied.')]
        [System.String]
        $Path,

        [Parameter(Mandatory=$true,HelpMessage='The path of the destination folder, into which the file will be copied.')]
        [System.String]
        $DestinationFolder,

        [Parameter(Mandatory=$true,HelpMessage='If the file needs to be removed during uninstall, then set this value to $true.')]
        [System.Boolean]
        $OverwriteExistingFile
    )

    begin {
        ####################################################################################################
        ### MAIN PROPERTIES ###

        # Input
        [System.String]$FileToCopyPath          = $Path
        [System.String]$FileToCopyLeaf          = (Split-Path -Path $FileToCopyPath -Leaf)
        [System.String]$FolderToCopyInto        = $DestinationFolder
        # Output
        [System.Boolean]$InstallationSuccess    = $null

        ####################################################################################################
    }
    
    process {
        # PREPARATION
        # Set the destination path
        [System.String]$DestinationFilePath = Join-Path -Path $FolderToCopyInto -ChildPath $FileToCopyLeaf

        # VALIDATION
        # If the file already exists, and the OverwriteExistingFile Boolean is set to false
        if ((Test-Path -Path $DestinationFilePath) -and ($OverwriteExistingFile -eq $false)) {
            Write-Line "The file already exists, and the OverwriteExistingFile Boolean has been set to False. ($DestinationFilePath)" -Type Success
            Write-Line "The application is considered installed. No action has been taken. ($DestinationFilePath)" -Type Success
            $InstallationSuccess = $true ; Return
        }

        # If the file already exists, and the OverwriteExistingFile Boolean is set to true
        if ((Test-Path -Path $DestinationFilePath) -and ($OverwriteExistingFile -eq $true)) {
            Write-Line "The file already exists, and the OverwriteExistingFile Boolean has been set to True. ($DestinationFilePath)" -Type Busy
            Write-Line "The file wil be overwritten. ($DestinationFilePath)" -Type Busy
        }

        # INSTALLATION
        try {
            # Install the file
            Write-Line "Installing the file ($FileToCopyLeaf). One moment please..." -Type Busy
            # Create the installation folder
            if (-Not(Test-Path -Path $FolderToCopyInto)) {
                Write-Line "Creating the Parent Folder... ($FolderToCopyInto)"
                New-Item -Path $FolderToCopyInto -ItemType Directory -Force | Out-Null
            }
            # Copy the file
            Write-Line "Copying the file from the sourcefolder ($FileToCopyPath) to the Installation Folder... ($FolderToCopyInto)"
            Copy-Item -Path $FileToCopyPath -Destination $FolderToCopyInto -Force
        }
        catch {
            Write-FullError
            $InstallationSuccess = $false
        }

        # TESTING
        if (Test-Path -Path $DestinationFilePath) {
            Write-Line "The file has been successfully installed. ($DestinationFilePath)" -Type Success
            $InstallationSuccess = $true
        } else {
            Write-Line "Something went wrong when copying the file. ($DestinationFilePath)" -Type Fail
            $InstallationSuccess = $false
        }
    }
    
    end {
        # Return the output
        $InstallationSuccess
    }
}

### END OF SCRIPT
####################################################################################################


####################################################################################################
<#
.SYNOPSIS
    This function removes a file, from a folder on the local system, for example C:\Program Files.
.DESCRIPTION
    This function is part of the Universal Deployment Script. It contains functions or variables, that are in other files.
.EXAMPLE
    Uninstall-BasicFile -SourceFolderPath 'C:\Demo\MyApplication1.0' -DestinationFolder 'C:\Program Files' -LeafName 'My Application 1.0'
.INPUTS
    [System.String]
.OUTPUTS
    [System.Boolean]
.NOTES
    Version         : 5.5.3
    Author          : Imraan Iotana
    Creation Date   : November 2025
    Last Update     : November 2025
.COPYRIGHT
    Copyright (C) Iotana. All rights reserved.
#>
####################################################################################################

function Uninstall-BasicFile {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true,HelpMessage='The path of the file that will be copied.')]
        [System.String]
        $Path,

        [Parameter(Mandatory=$true,HelpMessage='The path of the destination folder, into which the file will be copied.')]
        [System.String]
        $DestinationFolder,

        [Parameter(Mandatory=$true,HelpMessage='If the file needs to be removed during uninstall, then set this value to $true.')]
        [System.Boolean]
        $RemoveDuringUninstall
    )

    begin {
        ####################################################################################################
        ### MAIN PROPERTIES ###

        # Input
        [System.String]$SourceFilePath      = $Path
        [System.String]$FileToRemoveLeaf    = (Split-Path -Path $SourceFilePath -Leaf)
        [System.String]$FolderToRemoveFrom  = $DestinationFolder
        # Output
        [System.Boolean]$UninstallSuccess   = $null

        ####################################################################################################
    }
    
    process {
        # PREPARATION
        # Set the FileToRemove path
        [System.String]$FileToRemovePath = Join-Path -Path $FolderToRemoveFrom -ChildPath $FileToRemoveLeaf

        # VALIDATION
        # If the file does not exist
        if (-Not(Test-Path -Path $FileToRemovePath)) {
            Write-Line "The file is not present on the local system. ($FileToRemovePath)" -Type Busy
            Write-Line "The Uninstall is considered successful. No action has been taken. ($FileToRemovePath)" -Type Success
            $UninstallSuccess = $true ; Return
        }

        # If the file exists, and the RemoveDuringUninstall Boolean is set to false
        if ((Test-Path -Path $FileToRemovePath) -and ($RemoveDuringUninstall -eq $false)) {
            Write-Line "The file exists, but the RemoveDuringUninstall Boolean has been set to False. ($FileToRemovePath)" -Type Busy
            Write-Line "The Uninstall is considered successful. No action has been taken. ($FileToRemovePath)" -Type Success
            $UninstallSuccess = $true ; Return
        }

        # UNINSTALL
        try {
            # Remove the file
            Write-Line "Uninstalling the file ($FileToRemovePath). One moment please..." -Type Busy
            Remove-Item -Path $FileToRemovePath -Force
        }
        catch {
            Write-FullError
            $UninstallSuccess = $false
        }

        # TESTING
        if (Test-Path -Path $FileToRemovePath) {
            Write-Line "Something went wrong when removing the file. ($FileToRemovePath)" -Type Fail
            $UninstallSuccess = $false
        } else {
            Write-Line "The file has been successfully removed. ($FileToRemovePath)" -Type Success
            $UninstallSuccess = $true
        }
    }
    
    end {
        # Return the output
        $UninstallSuccess
    }
}

### END OF SCRIPT
####################################################################################################
