#
# MODULE Acl for 'ModuleSystem'
#
# Generated by: Imraan Iotana
#
# Generated on: 19-12-2025
#


####################################################################################################
<#
.SYNOPSIS
    This function sets the ACL of a folder to the ACL of its parent folder.
.DESCRIPTION
    This function is part of the Universal Deployment Script. It contains functions or variables, that are in other files.
.EXAMPLE
    Set-AclFromParentFolder -Path 'C:\Demo\MyNewFolder'
.EXAMPLE
    Set-AclFromParentFolder -Path 'C:\Program Files\MyApplication'
.INPUTS
    [System.String]
    [System.Management.Automation.SwitchParameter]
.OUTPUTS
    This function returns no stream-output.
.NOTES
    Version         : 5.6
    Author          : Imraan Iotana
    Creation Date   : December 2025
    Last Update     : December 2025
.COPYRIGHT
    Copyright (C) Iotana. All rights reserved.
#>
####################################################################################################

function Set-AclFromParentFolder {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true,HelpMessage='The folder of which the ACL will be changed.')]
        [System.String]
        $Path,

        [Parameter(Mandatory=$false,HelpMessage='Switch for using icacls instead of PowerShell.')]
        [System.Management.Automation.SwitchParameter]
        $UseIcacls
    )

    begin {
        ####################################################################################################
        ### MAIN PROPERTIES ###

        # Input
        [System.String]$FolderToChangeACL   = $Path

        # Handlers
        [System.String]$ParentFolder        = Split-Path -Path $FolderToChangeACL -Parent

        ####################################################################################################
    }
    
    process {
        # VALIDATION - FOLDER
        # If the path does not exist, return
        if (-Not(Test-Path -Path $FolderToChangeACL)) {
            Write-Line "The folder can not be reached. No action has been taken. ($FolderToChangeACL)" -Type Fail
            Write-Line -Type ValidationFail ; Return
        }

        # VALIDATON - ACL
        # Compare the two ACL's
        if (Compare-AclToParentFolder -Path $FolderToChangeACL) {
            Write-Line "The ACL of the Childfolder ($FolderToChangeACL) is the same as the Parentfolder. ($ParentFolder)" -Type Success
            Write-Line -Type SuccessNoAction
            Return
        } else {
            Write-Line "The ACL of the Childfolder ($FolderToChangeACL) is NOT the same as the Parentfolder. ($ParentFolder)"
        }

        # VALIDATION - ICACLS
        # Validate if icacls is present on the local system
        if ($UseIcacls.IsPresent) {
            [System.Management.Automation.ApplicationInfo]$IcaclsCommand = Get-Command icacls -ErrorAction SilentlyContinue
            if (-Not($IcaclsCommand)) {
                Write-Line "The command 'icacls' can not be found. Make sure icacls is installed, and the icacls.exe-folder is added to the System's PATH Variable." -Type Fail
                Write-Line -Type ValidationFail ; Return
            } else {
                Write-Line "The command 'icacls' was found. Using the following icacls-executable: ($($IcaclsCommand.Path))"
            }
        }

        # EXECUTION
        try {
            if ($UseIcacls.IsPresent) {
                # Using icacls:
                # Reset the ACl so it will inherit from the parent
                Write-Line "Resetting the permissions using icacls, so the ACL of the Parentfolder will be inherited... ($FolderToChangeACL)" -Type Busy
                Install-Executable -Path $IcaclsCommand.Path -AdditionalArguments "`"$FolderToChangeACL`" /reset /t /c /q"
            } else {
                # Use powershell
                # Set the ACL to that of the parent
                Write-Line "Equalizing the permissions using Set-Acl, to the ACL of the Parentfolder... ($FolderToChangeACL)" -Type Busy
                [System.Security.AccessControl.DirectorySecurity]$AclOfParentFolder = Get-Acl -Path $ParentFolder
                Set-Acl -Path $FolderToChangeACL -AclObject $AclOfParentFolder
            }
        }
        catch {
            Write-FullError
        }

        # TESTING
        # Compare the two ACL's
        if (Compare-AclToParentFolder -Path $FolderToChangeACL) {
            Write-Line "The ACL of the Childfolder ($FolderToChangeACL) is the same as the Parentfolder. ($ParentFolder)" -Type Success
            Return
        } else {
            Write-Line "The ACL of the Childfolder ($FolderToChangeACL) is NOT the same as the Parentfolder. ($ParentFolder)" -Type Fail
        }
    }
    
    end {
    }
}

### END OF SCRIPT
####################################################################################################



####################################################################################################
<#
.SYNOPSIS
    This function compares the ACL of a folder, to the ACL of its parent-folder. If they are equal, the function returns $true, else $false.
.DESCRIPTION
    This function is part of the Universal Deployment Script. It contains functions or variables, that are in other files.
.EXAMPLE
    Compare-AclToParentFolder -Path 'C:\Demo\MyNewFolder'
.EXAMPLE
    Compare-AclToParentFolder -Path 'C:\Program Files\MyApplication'
.INPUTS
    [System.String]
.OUTPUTS
    [System.Boolean]
.NOTES
    Version         : 5.6
    Author          : Imraan Iotana
    Creation Date   : December 2025
    Last Update     : December 2025
.COPYRIGHT
    Copyright (C) Iotana. All rights reserved.
#>
####################################################################################################

function Compare-AclToParentFolder {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true,HelpMessage='The folder of which the ACL will be checked.')]
        [System.String]
        $Path
    )

    begin {
        ####################################################################################################
        ### MAIN PROPERTIES ###

        # Input
        [System.String]$FolderToTest    = $Path

        # Output
        [System.Boolean]$OutputObject   = $null

        # Handlers
        [System.String]$ParentFolder    = Split-Path -Path $FolderToTest -Parent

        ####################################################################################################
    }
    
    process {
        # VALIDATION - FOLDER
        # If the path does not exist, return
        if (-Not(Test-Path -Path $FolderToTest)) {
            Write-Line "The folder can not be reached. ($FolderToTest)" -Type Fail
            Write-Line -Type ValidationFail ; Return
        }

        # EXECUTION
        # Get the ACL's
        [System.Security.AccessControl.AuthorizationRuleCollection]$AclOfParentFolder = (Get-Acl -Path $ParentFolder).Access
        [System.Security.AccessControl.AuthorizationRuleCollection]$AclOfChildFolder  = (Get-Acl -Path $FolderToTest).Access
        # Compare the two ACL's
        Write-Line "Comparing the ACL of the Childfolder ($FolderToTest) to the ACL of the Parent-folder. ($ParentFolder)"
        [System.Object[]]$Result = Compare-Object -ReferenceObject $AclOfParentFolder -DifferenceObject $AclOfChildFolder
        [System.Boolean]$ACLsAreEqual = if ($null -eq $Result) {
            Write-Line "The ACL of the Childfolder ($FolderToTest) is the same as the Parent-folder. ($ParentFolder)"
            $true
        } else {
            Write-Line "The ACL of the Childfolder ($FolderToTest) is NOT the same as the Parent-folder. ($ParentFolder)"
            $false
        }

        # Set the output
        $OutputObject = $ACLsAreEqual
    }
    
    end {
        # Return the output
        $OutputObject
    }
}

### END OF SCRIPT
####################################################################################################
