#
# MODULE Registry for 'ModuleSystem'
#
# Generated by: Imraan Iotana
#
# Generated on: 08-12-2025
#


####################################################################################################
<#
.SYNOPSIS
    This function import a REG file into the Registry.
.DESCRIPTION
    This function is part of the Universal Deployment Script. It contains functions or variables, that are in other files.
.EXAMPLE
    Start-REGFileDeployment -DeploymentObject $MyObject -Action 'Install'
.INPUTS
    [PSCustomObject]
    [System.String]
.OUTPUTS
    [System.Boolean]
.NOTES
    Version         : 5.5.3
    Author          : Imraan Iotana
    Creation Date   : November 2025
    Last Update     : November 2025
.COPYRIGHT
    Copyright (C) Iotana. All rights reserved.
#>
####################################################################################################

function Start-REGFileDeployment {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true,HelpMessage='The object containing the needed information')]
        [PSCustomObject]
        $DeploymentObject,

        [Parameter(Mandatory=$false,HelpMessage='The action that will be performed')]
        [ValidateSet('Install','Uninstall','Reinstall')]
        [System.String]
        $Action = 'Install'
    )

    begin {
        ####################################################################################################
        ### MAIN PROPERTIES ###

        # Input
        [System.String]$REGFileBaseName         = $DeploymentObject.REGFileBaseName
        # Output
        [System.Boolean]$DeploymentSuccess      = $null
        # Handlers
        [System.String]$REGExecutablePath       = $Global:DeploymentObject.REGExecutablePath

        ####################################################################################################
    }
    
    process {
        # VALIDATION - ACTION
        # Validate the action
        switch ($Action) {
            'Install'   {
                if ($DeploymentObject.ImportDuringInstall -eq $false) {
                    # Write the message and return true
                    Write-Line "The ImportDuringInstall boolean has been set to False. The REG file will not be imported during the $Action process." -Type Success
                    Write-Line -Type SuccessNoAction ; $DeploymentSuccess = $true ; Return
                }
            }
            'Uninstall' {
                if ($DeploymentObject.ImportDuringUninstall -eq $false) {
                    # Write the message and return true
                    Write-Line "The ImportDuringUninstall boolean has been set to False. The REG file will not be imported during the $Action process." -Type Success
                    Write-Line -Type SuccessNoAction ; $DeploymentSuccess = $true ; Return
                }
            }
        }

        # VALIDATION - FILE
        # Validate the RegFile
        if (Test-String -IsEmpty $REGFileBaseName) { Write-Line "The REGFileBaseName string is empty." -Type Fail ; Return }
        [System.String]$REGFilePath = Get-SourceItemPath -FileName "$REGFileBaseName.reg"
        if (-Not($REGFilePath)) { Write-Line -Type ValidationFail ; Return }

        # VALIDATION - SUCCESS
        # Write the success message
        Write-Line -Type ValidationSuccess


        # EXECUTION
        # Import the REG file
        Write-Line "Importing the REG file into the Registry... ($REGFilePath)" -Type Busy
        $DeploymentSuccess = try {
            Install-Executable -Path $REGExecutablePath -AdditionalArguments ('import', ('"{0}"' -f $REGFilePath) )
        }
        catch {
            Write-FullError
        }
    }
    
    end {
        # Return the output
        $DeploymentSuccess
    }
}

### END OF SCRIPT
####################################################################################################
