#
# MODULE LocalGroup for 'ModuleSystem'
#
# Generated by: Imraan Iotana
#
# Generated on: 08-12-2025
#

####################################################################################################
<#
.SYNOPSIS
    This function deploys a Local Group.
.DESCRIPTION
    This function is part of the Universal Deployment Script. It contains functions or variables, that are in other files.
.EXAMPLE
    Start-LocalGroupDeployment -DeploymentObject $MyObject -Action 'Install'
.INPUTS
    [PSCustomObject]
    [System.String]
.OUTPUTS
    [System.Boolean]
.NOTES
    Version         : 5.5.3
    Author          : Imraan Iotana
    Creation Date   : December 2025
    Last Update     : December 2025
.COPYRIGHT
    Copyright (C) Iotana. All rights reserved.
#>
####################################################################################################

function Start-LocalGroupDeployment {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true,HelpMessage='The object containing the needed information')]
        [PSCustomObject]
        $DeploymentObject,

        [Parameter(Mandatory=$false,HelpMessage='The action that will be performed')]
        [ValidateSet('Install','Uninstall','Reinstall')]
        [System.String]
        $Action = 'Install'
    )

    begin {
        ####################################################################################################
        ### MAIN PROPERTIES ###

        # Input
        [System.String]$LocalGroupName              = $DeploymentObject.LocalGroupName
        [System.String]$LocalGroupDescription       = $DeploymentObject.Description
        [System.String[]]$ParentGroupsArray         = $DeploymentObject.MakeMemberOfParentGroups
        [System.String[]]$MemberUsersOrGroupsToAdd  = $DeploymentObject.AddMemberUsersOrGroups

        # Output
        [System.Boolean]$DeploymentSuccess      = $null

        ####################################################################################################
    }
    
    process {
        # VALIDATION - ACTION
        # Validate the action
        switch ($Action) {
            'Install'   {
                if ($DeploymentObject.CreateDuringInstall -eq $false) {
                    # Write the message and return true
                    Write-Line "The CreateDuringInstall boolean has been set to False. The Local Group will not be created during the $Action process." -Type Success
                    Write-Line -Type SuccessNoAction ; $DeploymentSuccess = $true ; Return
                }
            }
            'Uninstall' {
                if ($DeploymentObject.RemoveDuringUninstall -eq $false) {
                    # Write the message and return true
                    Write-Line "The RemoveDuringUninstall boolean has been set to False. The Local Group will not be removed during the $Action process." -Type Success
                    Write-Line -Type SuccessNoAction ; $DeploymentSuccess = $true ; Return
                }
            }
        }

        # VALIDATION - LOCALGROUP
        # Validate the LocalGroupName
        if (Test-String -IsEmpty $LocalGroupName) { Write-Line "The LocalGroupName string is empty." -Type Fail ; Return }

        # VALIDATION - SUCCESS
        # Write the success message
        Write-Line -Type ValidationSuccess


        # EXECUTION
        $DeploymentSuccess = try {
            switch ($Action) {
                'Install'   {
                    # Validate the Local Group's existence
                    if (Test-LocalGroup -Name $LocalGroupName -OutHost -PassThru) {
                        Write-Line "The Local Group already exists. ($LocalGroupName)" -Type Success
                        Write-Line -Type SuccessNoAction
                        $true
                    } else {
                        # Create the LocalGroup
                        Write-Line "Creating the Local Group... ($LocalGroupName)" -Type Busy
                        New-LocalGroup -Name $LocalGroupName -Description $LocalGroupDescription
                        # Test the creation
                        if (Test-LocalGroup -Name $LocalGroupName -OutHost -PassThru) {
                            Write-Line "The Local Group has been successfully created. ($LocalGroupName)" -Type Success
                            $true
                        } else {
                            Write-Line "The Local Group could not be found. The Creation of the Local Group failed. ($LocalGroupName)" -Type Fail
                            $false
                        }
                    }
                }
                'Uninstall' {
                    # Validate the Local Group's existence
                    if (-Not(Test-LocalGroup -Name $LocalGroupName -OutHost -PassThru)) {
                        Write-Line "The Local Group does not exist. ($LocalGroupName)" -Type Success
                        Write-Line -Type SuccessNoAction
                        $true
                    } else {
                        # Remove the LocalGroup
                        Write-Line "Removing the Local Group... ($LocalGroupName)" -Type Busy
                        Remove-LocalGroup -Name $LocalGroupName
                        # Test the removal
                        if (Test-LocalGroup -Name $LocalGroupName -OutHost -PassThru) {
                            Write-Line "The Local Group still exists. The Removal of the Local Group failed. ($LocalGroupName)" -Type Fail
                            $false
                        } else {
                            Write-Line "The Local Group ($LocalGroupName) has been successfully removed." -Type Success
                            $true
                        }
                    }
                }
            }
        }
        catch {
            Write-FullError
        }

        # Perform the membership actions
        if (($Action -eq 'Install') -and ($DeploymentSuccess -eq $true)) {
            # Make the group a member of the parent groups
            if ($ParentGroupsArray.Count -eq 0) {
                Write-Line "The MakeMemberOfParentGroups array is empty. The new local group ($LocalGroupName) will not be added to another group."
            } else {
                $DeploymentSuccess = Add-LocalGroupToParentGroups -LocalGroupName $LocalGroupName -ParentGroupNames $ParentGroupsArray -PassThru
            }
            # Add the members to the new local group
            if ($MemberUsersOrGroupsToAdd.Count -eq 0) {
                Write-Line "The AddMemberUsersOrGroups array is empty. No members will be added to the new local group ($LocalGroupName)."
            } else {
                $DeploymentSuccess = $DeploymentSuccess = Add-MembersToLocalGroup -LocalGroupName $LocalGroupName -MemberNames $MemberUsersOrGroupsToAdd -PassThru
            }
        }
    }
    
    end {
        # Return the output
        $DeploymentSuccess
    }
}

### END OF SCRIPT
####################################################################################################


####################################################################################################
<#
.SYNOPSIS
    This function tests if a Local Group exists.
.DESCRIPTION
    This function is part of the Universal Deployment Script. It contains functions or variables, that are in other files.
.EXAMPLE
    Test-LocalGroup -Name 'Adobe Administrators'
.INPUTS
    [System.String]
    [System.Management.Automation.SwitchParameter]
.OUTPUTS
    [System.Boolean]
.NOTES
    Version         : 5.5.3
    Author          : Imraan Iotana
    Creation Date   : December 2025
    Last Update     : December 2025
.COPYRIGHT
    Copyright (C) Iotana. All rights reserved.
#>
####################################################################################################

function Test-LocalGroup {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true,HelpMessage='The name of the local group that will be checked.')]
        [System.String]
        $Name,

        [Parameter(Mandatory=$false,HelpMessage='Switch for writing the details to the host.')]
        [System.Management.Automation.SwitchParameter]
        $OutHost,

        [Parameter(Mandatory=$false,HelpMessage='Switch for returning the result as a boolean.')]
        [System.Management.Automation.SwitchParameter]
        $PassThru
    )

    begin {
        ####################################################################################################
        ### MAIN PROPERTIES ###

        # Input
        [System.String]$LocalGroupNameToTest = $Name

        # Output
        [System.Boolean]$LocalGroupExists = $null

        ####################################################################################################
    }
    
    process {
        # EXECUTION
        # Test if the Local Group exists
        if ($OutHost) { Write-Line "Testing if the Local Group exists... ($LocalGroupNameToTest)" }
        [Microsoft.PowerShell.Commands.LocalPrincipal]$LocalGroupObject = Get-LocalGroup -Name $LocalGroupNameToTest -ErrorAction SilentlyContinue
        # Set the output
        $LocalGroupExists = if ($LocalGroupObject) {
            if ($OutHost) { Write-Line "The Local Group exists... ($LocalGroupNameToTest)" }
            $true
        } else {
            if ($OutHost) { Write-Line "The Local Group does NOT exist... ($LocalGroupNameToTest)" }
            $false
        }
    }
    
    end {
        # Return the output
        if ($PassThru) { $LocalGroupExists }
    }
}

### END OF SCRIPT
####################################################################################################


####################################################################################################
<#
.SYNOPSIS
    This function adds a Local Group to another Local Group.
.DESCRIPTION
    This function is part of the Universal Deployment Script. It contains references to classes, functions or variables, that are in other files.
.EXAMPLE
    Add-LocalGroupToParentGroups -LocalGroupName 'MyNewGroup' -ParentGroupNames ('Administrators','Guests')
.INPUTS
    [System.String]
    [System.String[]]
    [System.Management.Automation.SwitchParameter]
.OUTPUTS
    [System.Boolean]
.NOTES
    Version         : 5.5.3
    Author          : Imraan Iotana
    Creation Date   : December 2025
    Last Update     : December 2025
.COPYRIGHT
    Copyright (C) Iotana. All rights reserved.
#>
####################################################################################################

function Add-LocalGroupToParentGroups {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true,HelpMessage='The Local Group that will be added to the Parent Group.')]
        [System.String]
        $LocalGroupName,

        [Parameter(Mandatory=$true,HelpMessage='The Parent Groups to which The Local Group will be added.')]
        [System.String[]]
        $ParentGroupNames,

        [Parameter(Mandatory=$false,HelpMessage='Switch for returning the result as a boolean.')]
        [System.Management.Automation.SwitchParameter]
        $PassThru
    )

    begin {
        ####################################################################################################
        ### MAIN PROPERTIES ###

        # Input
        [System.String]$GroupToAddToParent  = $LocalGroupName
        [System.String[]]$ParentGroupsArray = $ParentGroupNames

        # Output
        [System.Boolean]$MembershipSuccess  = $null

        ####################################################################################################
    }
    
    process {
        # VALIDATION
        # If the array is empty
        if ($ParentGroupsArray.Count -eq 0) {
            Write-Line "The ParentGroupNames-array is empty. The Local Group has NOT been made a member of another group. ($GroupToAddToParent)"
            Write-Line "The Membership-action is considered sucessful. No action has been taken." -Type Success ; $MembershipSuccess = $true ; Return
        }

        # EXECUTION
        try {
            foreach ($ParentGroupName in $ParentGroupsArray) {
                Write-Line "Adding the Local Group ($GroupToAddToParent) to the Local Parent Group ($ParentGroupName)." -Type Busy
                Add-LocalGroupMember -Group $ParentGroupName -Member $GroupToAddToParent -ErrorAction Stop
                Write-Line "The Local Group ($GroupToAddToParent) has been made a member of the Parent Group ($ParentGroupName)." -Type Success
            }
            $MembershipSuccess = $true
        }
        catch [Microsoft.PowerShell.Commands.MemberExistsException] {
            Write-Line "The Local Group ($GroupToAddToParent) was already a member of the Local Parent Group ($ParentGroupName). No action has been taken." -Type Success
            $MembershipSuccess = $true

        }
        catch {
            Write-Line "An error occured while adding the Local Group ($GroupToAddToParent) to the Local Parent Group ($ParentGroupName)." -Type Fail
            Write-FullError
        }
    }
    
    end {
        # Return the output
        if ($PassThru) { $MembershipSuccess }
    }
}

### END OF SCRIPT
####################################################################################################


####################################################################################################
<#
.SYNOPSIS
    This function adds members to a Local Group.
.DESCRIPTION
    This function is part of the Universal Deployment Script. It contains functions or variables, that are in other files.
.EXAMPLE
    Add-MembersToLocalGroup -LocalGroupName 'MyNewLocalGroup' -MemberNames ('Users','Domain\MyNewADGroup') -PassThru
.INPUTS
    [System.String]
    [System.String[]]
    [System.Management.Automation.SwitchParameter]
.OUTPUTS
    [System.Boolean]
.NOTES
    Version         : 5.5.3
    Author          : Imraan Iotana
    Creation Date   : December 2025
    Last Update     : December 2025
.COPYRIGHT
    Copyright (C) Iotana. All rights reserved.
#>
####################################################################################################

function Add-MembersToLocalGroup {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true,HelpMessage='The Local Group to which the Members will be added.')]
        [System.String]
        $LocalGroupName,

        [Parameter(Mandatory=$true,HelpMessage='The Members that will be added to the Local Group.')]
        [System.String[]]
        $MemberNames,

        [Parameter(Mandatory=$false,HelpMessage='Switch for returning the result as a boolean.')]
        [System.Management.Automation.SwitchParameter]
        $PassThru
    )

    begin {
        ####################################################################################################
        ### MAIN PROPERTIES ###

        # Input
        [System.String]$LocalGroupToAddMembersTo    = $LocalGroupName
        [System.String[]]$MembersToAddToLocalGroup  = $MemberNames

        # Output
        [System.Boolean]$MembershipSuccess  = $null

        ####################################################################################################
    }
    
    process {
        # VALIDATION
        # If the array is empty
        if ($MembersToAddToLocalGroup.Count -eq 0) {
            Write-Line "The MemberNames-array is empty. No members have been added to the Local. ($LocalGroupToAddMembersTo)"
            Write-Line "The Membership-action is considered sucessful. No action has been taken." -Type Success ; $MembershipSuccess = $true ; Return
        }

        # EXECUTION
        try {
            foreach ($MemberName in $MembersToAddToLocalGroup) {
                Write-Line "Adding the Member ($MemberName) to the Local Group ($LocalGroupToAddMembersTo)..." -Type Busy
                Add-LocalGroupMember -Group $LocalGroupToAddMembersTo -Member $MemberName -ErrorAction Stop
                Write-Line "The Member ($MemberName) has been added to the Local Group ($LocalGroupToAddMembersTo)." -Type Success
            }
            $MembershipSuccess = $true
        }
        catch [Microsoft.PowerShell.Commands.MemberExistsException] {
            Write-Line "The Member ($MemberName) was already a member of the Local Group ($LocalGroupToAddMembersTo). No action has been taken." -Type Success
            $MembershipSuccess = $true

        }
        catch {
            Write-Line "An error occured while adding the Member ($MemberName) to the Local Group ($LocalGroupToAddMembersTo)." -Type Fail
            Write-Line "Please make sure this machine is domain-joined ($($ENV:COMPUTERNAME)) and that this account has the necessary permissions ($($ENV:USERNAME))." -Type Fail
            Write-FullError
        }
    }
    
    end {
        # Return the output
        if ($PassThru) { $MembershipSuccess }
    }
}

### END OF SCRIPT
####################################################################################################


####################################################################################################
<#
.SYNOPSIS
    This function removes a user from a Local Group.
.DESCRIPTION
    This function is part of the Universal Deployment Script. It contains functions or variables, that are in other files.
.EXAMPLE
    Start-RemoveLocalUserDeployment -DeploymentObject $MyObject -Action 'Install'
.INPUTS
    [PSCustomObject]
    [System.String]
.OUTPUTS
    [System.Boolean]
.NOTES
    Version         : 5.5.3
    Author          : Imraan Iotana
    Creation Date   : November 2025
    Last Update     : November 2025
.COPYRIGHT
    Copyright (C) Iotana. All rights reserved.
#>
####################################################################################################

function Start-RemoveUserFromLocalGroup {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true,HelpMessage='The object containing the needed information')]
        [PSCustomObject]
        $DeploymentObject,

        [Parameter(Mandatory=$false,HelpMessage='The action that will be performed')]
        [ValidateSet('Install','Uninstall','Reinstall')]
        [System.String]
        $Action = 'Install'
    )

    begin {
        ####################################################################################################
        ### MAIN PROPERTIES ###

        # Input
        [System.String]$LocalGroupName      = $DeploymentObject.LocalGroupName

        # Output
        [System.Boolean]$DeploymentSuccess  = $null

        ####################################################################################################
        ### INTERNAL FUNCTIONS

        function Remove-LocalGroupMemberInternal { param ([System.String]$LocalGroupName,[System.String]$MemberNameToRemove)
            # Remove the member
            Write-Line "Removing the Member ($MemberNameToRemove) from the Local Group ($LocalGroupName). One moment please..." -Type Busy
            Remove-LocalGroupMember -Group $LocalGroupName -Member $MemberNameToRemove
            Write-Line "The Member ($MemberNameToRemove) has been removed from the Local Group ($LocalGroupName)." -Type Success
            # Return true
            $true
        }

        ####################################################################################################
    }
    
    process {
        # VALIDATION - ACTION
        # Validate the action
        switch ($Action) {
            'Install'   {
                if ($DeploymentObject.RemoveDuringInstall -eq $false) {
                    # Write the message and return true
                    Write-Line "The RemoveDuringInstall boolean has been set to False. The Member will not be removed during the $Action process." -Type Success
                    Write-Line -Type SuccessNoAction ; $DeploymentSuccess = $true ; Return
                }
            }
            'Uninstall' {
                if ($DeploymentObject.RemoveDuringUninstall -eq $false) {
                    # Write the message and return true
                    Write-Line "The RemoveDuringUninstall boolean has been set to False. The Member will not be removed during the $Action process." -Type Success
                    Write-Line -Type SuccessNoAction ; $DeploymentSuccess = $true ; Return
                }
            }
        }

        # VALIDATION - MEMBERS
        # Validate both the Member properties
        if ((Test-String -IsEmpty $DeploymentObject.MemberNameToRemove) -and (Test-String -IsEmpty $DeploymentObject.MemberSIDToRemove)) {
            Write-Line "Both the MemberNameToRemove AND the MemberSIDToRemove strings are empty. One of these is mandatory." -Type Fail ; Return
        }
        if ((Test-String -IsPopulated $DeploymentObject.MemberNameToRemove) -and (Test-String -IsPopulated $DeploymentObject.MemberSIDToRemove)) {
            Write-Line "Both the MemberNameToRemove AND the MemberSIDToRemove strings are filled. Please remove one." -Type Fail ; Return
        }

        # VALIDATION - GROUP
        # Validate the LocalGroupName
        if (Test-String -IsEmpty $LocalGroupName) { Write-Line "The LocalGroupName string is empty." -Type Fail ; Return }
        # Validate the group existence
        [Microsoft.PowerShell.Commands.LocalGroup]$LocalGroupOnSystem = Get-LocalGroup | Where-Object { $_.Name -eq $LocalGroupName }
        if (-Not($LocalGroupOnSystem)) { Write-Line "The Local Group can not be found. ($LocalGroupName)" -Type Fail ; Return }
        # Write the message
        Write-Line -Type ValidationSuccess


        # PREPARATION - MEMBERNAME
        # Test if the MemberNameToRemove is a member of the local group
        if (Test-String -IsPopulated $DeploymentObject.MemberNameToRemove ) {
            [System.String]$MemberNameToRemove = $DeploymentObject.MemberNameToRemove
            [System.String[]]$GroupMemberNames = (Get-LocalGroupMember -Group $LocalGroupName).Name
            if ($GroupMemberNames -contains $MemberNameToRemove) {
                # Write the message
                Write-Line "The Local Group ($LocalGroupName) contains the Member name ($MemberNameToRemove)."
            } else {
                # Write the message and return true
                Write-Line "The Local Group ($LocalGroupName) does NOT contain the Member name ($MemberNameToRemove)." -Type Success
                Write-Line -Type SuccessNoAction ; $DeploymentSuccess = $true ; Return
            }
        }

        # PREPARATION - MEMBERSID
        # Test if the MemberSIDToRemove is a member of the local group
        if (Test-String -IsPopulated $DeploymentObject.MemberSIDToRemove ) {
            [System.String]$MemberSIDToRemove = $DeploymentObject.MemberSIDToRemove
            [System.String[]]$GroupMemberSIDs = (Get-LocalGroupMember -Group $LocalGroupName).SID
            if ($GroupMemberSIDs -contains $MemberSIDToRemove) {
                # Write the message
                Write-Line "The Local Group ($LocalGroupName) contains the Member SID ($MemberSIDToRemove)."
                # Set the MemberNameToRemove based on the SID
                [System.String]$MemberNameToRemove = (Get-LocalGroupMember -Group $LocalGroupName | Where-Object { $_.SID -eq $MemberSIDToRemove }).Name
                Write-Line "Resolving the Member SID ($MemberSIDToRemove) to the Member Name ($MemberNameToRemove)." -Type Busy
            } else {
                # Write the message and return true
                Write-Line "The Local Group ($LocalGroupName) does NOT contain the Member SID ($MemberSIDToRemove)." -Type Success
                Write-Line -Type SuccessNoAction ; $DeploymentSuccess = $true ; Return
            }
        }

        # EXECUTION
        # Remove the member
        $DeploymentSuccess = try {
            Remove-LocalGroupMemberInternal -LocalGroupName $LocalGroupName -MemberNameToRemove $MemberNameToRemove
        }
        catch {
            # Write the error and return false
            Write-FullError
            $false
        }
    }
    
    end {
        # Return the output
        $DeploymentSuccess
    }
}

### END OF SCRIPT
####################################################################################################
