#
# MODULE SystemPath for 'ModuleSystem'
#
# Generated by: Imraan Iotana
#
# Generated on: 09-12-2025
#


####################################################################################################
<#
.SYNOPSIS
    This function deploys a Directory to the System's PATH Environment Variable.
.DESCRIPTION
    This function is part of the Universal Deployment Script. It contains functions or variables, that are in other files.
.EXAMPLE
    Start-SystemPathDeployment -DeploymentObject $MyObject -Action 'Install'
.INPUTS
    [PSCustomObject]
    [System.String]
.OUTPUTS
    [System.Boolean]
.NOTES
    Version         : 5.5.2
    Author          : Imraan Iotana
    Creation Date   : October 2025
    Last Update     : November 2025
.COPYRIGHT
    Copyright (C) Iotana. All rights reserved.
#>
####################################################################################################

function Start-SystemPathDeployment {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true,HelpMessage='The object containing the needed information')]
        [PSCustomObject]
        $DeploymentObject,

        [Parameter(Mandatory=$false,HelpMessage='The action that will be performed')]
        [ValidateSet('Install','Uninstall','Reinstall')]
        [System.String]
        $Action = 'Install'
    )

    begin {
        ####################################################################################################
        ### MAIN PROPERTIES ###

        # Function
        [System.String]$PreFix              = "[$($MyInvocation.MyCommand)]:"
        # Handlers
        [System.String]$DirectoryToHandle   = $DeploymentObject.Directory
        # Output
        [System.Boolean]$DeploymentSuccess  = $null

        ####################################################################################################
    }
    
    process {
        # VALIDATION 
        # If the validation failed, then return
        if (Test-String -IsEmpty $DirectoryToHandle) { Write-Line -Type ValidationFail ; Return }

        # VALIDATION - SUCCESS
        # Write the message
        Write-Line -Type ValidationSuccess

        # EXECUTION
        try {
            $DeploymentSuccess = switch ($Action) {
                'Install'   {
                    if ($DeploymentObject.AddDuringInstall) { Add-SystemPath -Path $DirectoryToHandle } else { Write-Success "$PreFix The AddDuringInstall Boolean has been set to False. No action has been taken." ; $true }
                }
                'Uninstall' {
                    if ($DeploymentObject.RemoveDuringUninstall) { Remove-SystemPath -Path $DirectoryToHandle } else { Write-Success "$PreFix The RemoveDuringUninstall Boolean has been set to False. No action has been taken." ; $true }
                }
            }
        }
        catch {
            Write-FullError
        }
    }
    
    end {
        # Return the output
        $DeploymentSuccess
    }
}

### END OF SCRIPT
####################################################################################################


####################################################################################################
<#
.SYNOPSIS
    This function tests if a Directory is part of the System's PATH Environment Variable.
.DESCRIPTION
    This function is part of the Universal Deployment Script. It contains references to classes, functions or variables, that are in other files.
.EXAMPLE
    Test-SystemPath -Path 'C:\Program Files\MyNewApplication'
.INPUTS
    [System.String]
.OUTPUTS
    [System.Boolean]
.NOTES
    Version         : 5.5.2
    Author          : Imraan Iotana
    Creation Date   : October 2025
    Last Update     : November 2025
.COPYRIGHT
    Copyright (C) Iotana. All rights reserved.
#>
####################################################################################################

function Test-SystemPath {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true,HelpMessage='The directory that will be tested.')]
        [Alias('Directory','DirectoryToAdd','PathToAdd')]
        [System.String]
        $Path,

        [Parameter(Mandatory=$false,HelpMessage='Switch for writing the details to the host.')]
        [System.Management.Automation.SwitchParameter]
        $OutHost,

        [Parameter(Mandatory=$false,HelpMessage='Switch for returning the result as a boolean.')]
        [System.Management.Automation.SwitchParameter]
        $PassThru
    )

    begin {
        ####################################################################################################
        ### MAIN PROPERTIES ###

        # Input
        [System.String]$DirectoryToAdd  = $Path

        # Output
        [System.Boolean]$TestResult     = $null

        ####################################################################################################
    }
    
    process {
        # VALIDATION
        # Get the Path
        [System.String]$SystemPath = [Environment]::GetEnvironmentVariable('Path','Machine')
        if (Test-String -IsEmpty $SystemPath) { Write-Line "The SYSTEM PATH Variable is empty, or could not be obtained." -Type Fail ; Return }
        # Split the Path into an array
        [System.String[]]$PathArray = $SystemPath.Split(';')
        if ($PathArray.Count -eq 0) { Write-Line "The SYSTEM PATH Variable does not contain any content." -Type Fail ; Return }

        
        # EXECUTION
        # Test if the array contains the directory
        if ($OutHost) { Write-Line "Testing if the the SYSTEM PATH contains the directory... ($DirectoryToAdd)" }
        [System.Boolean]$TestResult = ($PathArray -contains $DirectoryToAdd)
        if ($OutHost) {
            if ($TestResult -eq $true) {
                Write-Line "The SYSTEM PATH contains the directory ($DirectoryToAdd)."
            } else {
                Write-Line "The SYSTEM PATH does NOT contain the directory ($DirectoryToAdd)."
            }
        }
    }
    
    end {
        # Return the output
        if ($PassThru) { $TestResult }
    }
}

### END OF SCRIPT
####################################################################################################


####################################################################################################
<#
.SYNOPSIS
    This function adds a Directory to the System's PATH Environment Variable.
.DESCRIPTION
    This function is part of the Universal Deployment Script. It contains references to classes, functions or variables, that are in other files.
.EXAMPLE
    Add-SystemPath -Path 'C:\Program Files\MyNewApplication'
.INPUTS
    [System.String]
.OUTPUTS
    [System.Boolean]
.NOTES
    Version         : 5.5.2
    Author          : Imraan Iotana
    Creation Date   : October 2025
    Last Update     : November 2025
.COPYRIGHT
    Copyright (C) Iotana. All rights reserved.
#>
####################################################################################################

function Add-SystemPath {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true,HelpMessage='The directory that will be added to the Systems PATH Environment Variable.')]
        [Alias('Directory','DirectoryToAdd','PathToAdd')]
        [System.String]
        $Path
    )

    begin {
        ####################################################################################################
        ### MAIN PROPERTIES ###

        #Input
        [System.String]$DirectoryToAdd      = $Path
        # Output
        [System.Boolean]$DeploymentSuccess  = $null

        ####################################################################################################
    }
    
    process {
        # VALIDATION
        # If the directory is already in the SYSTEM PATH then return
        if (Test-SystemPath -Path $DirectoryToAdd -OutHost -PassThru) {
            Write-Line "The directory ($DirectoryToAdd) is already part of the PATH Variable. No action has been taken." -Type Success ; $DeploymentSuccess = $true ; Return
        }

        # EXECUTION
        # Get the SYSTEM PATH
        [System.String]$SystemPath = [Environment]::GetEnvironmentVariable('Path','Machine')
        # Add the directory to the array
        Write-Line "Adding the directory ($DirectoryToAdd) to the PATH Variable." -Type Busy
        [System.String]$NEWSystemPath = "$SystemPath;$DirectoryToAdd"
        # Set the SYSTEM PATH
        [Environment]::SetEnvironmentVariable('Path',$NEWSystemPath,'Machine')

        # TESTING        
        $DeploymentSuccess = if (Test-SystemPath -Path $DirectoryToAdd -OutHost -PassThru) {
            Write-Line "The directory ($DirectoryToAdd) has been added successfully to the PATH Variable." -Type Success ; $true
        } else {
            Write-Line "The directory ($DirectoryToAdd) has NOT been added to the PATH Variable. An unknown error has occured." -Type Fail ; $false
        }
    }
    
    end {
        # Return the output
        $DeploymentSuccess
    }
}

### END OF SCRIPT
####################################################################################################


####################################################################################################
<#
.SYNOPSIS
    This function removes a Directory from the System's PATH Environment Variable.
.DESCRIPTION
    This function is part of the Universal Deployment Script. It contains references to classes, functions or variables, that are in other files.
.EXAMPLE
    Remove-SystemPath -Path 'C:\Program Files\MyNewApplication'
.INPUTS
    [System.String]
.OUTPUTS
    [System.Boolean]
.NOTES
    Version         : 5.5.1
    Author          : Imraan Iotana
    Creation Date   : October 2025
    Last Update     : November 2025
.COPYRIGHT
    Copyright (C) Iotana. All rights reserved.
#>
####################################################################################################

function Remove-SystemPath {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true,HelpMessage='The directory that will be removed from the Systems PATH Environment Variable.')]
        [Alias('Directory','DirectoryToRemove','PathToAdd')]
        [System.String]
        $Path
    )

    begin {
        ####################################################################################################
        ### MAIN PROPERTIES ###

        #Input
        [System.String]$DirectoryToRemove   = $Path
        # Output
        [System.Boolean]$DeploymentSuccess  = $null

        ####################################################################################################
    }
    
    process {
        # VALIDATION
        # If the directory is NOT in the SYSTEM PATH then return
        if (-Not(Test-SystemPath -Path $DirectoryToRemove -OutHost -PassThru)) {
            Write-Line "The directory ($DirectoryToRemove) is NOT part of the PATH Variable. No action has been taken." -Type Success ; $DeploymentSuccess = $true ; Return
        }

        # PREPARATION
        # Get the SYSTEM PATH
        [System.String]$CurrentSystemPath = [Environment]::GetEnvironmentVariable('Path','Machine')
        # Remove the directory from the array
        Write-Line "Removing the directory ($DirectoryToRemove) from the PATH Variable." -Type Busy
        [System.String]$NEWSystemPath = ($CurrentSystemPath.Split(';') | Where-Object { $_ -ne $DirectoryToRemove}) -join ';'
        # Set the new SYSTEM PATH
        [Environment]::SetEnvironmentVariable('Path',$NEWSystemPath,'Machine')

        # TESTING        
        $DeploymentSuccess = if (Test-SystemPath -Path $DirectoryToRemove -OutHost -PassThru) {
            Write-Line "The directory ($DirectoryToRemove) has NOT been removed from the PATH Variable. An unknown error has occured." -Type Fail ; $false
        } else {
            Write-Line "The directory ($DirectoryToRemove) has been removed from the PATH Variable." -Type Success ; $true
        }
    }
    
    end {
        # Return the output
        $DeploymentSuccess
    }
}

### END OF SCRIPT
####################################################################################################
