#
# ROOT MODULE for module 'ModuleWrite'
#
# Generated by: Imraan Iotana
#
# Generated on: 28-8-2025
#


####################################################################################################
<#
.SYNOPSIS
    This function write a line to the host, in the colors assigned to this action.
.DESCRIPTION
    This function is self-contained and does not refer to functions, variables or classes, that are in other files.
.EXAMPLE
    Write-Busy "Hello World!"
.INPUTS
    [System.String]
.OUTPUTS
    This function returns no stream output.
.NOTES
    Version         : 5.5.1
    Author          : Imraan Iotana
    Creation Date   : September 2025
    Last Update     : September 2025
#>
####################################################################################################

function Write-Busy {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true,Position=0,HelpMessage='The message that will be written to the host.')]
        [AllowNull()]
        [AllowEmptyString()]
        [System.String]
        $Message
    )

    begin {
        # Handlers
        [System.String]$TimeStamp               = Get-TimeStamp -ForLogging
        [System.String]$MessageWithTimeStamp    = "[$TimeStamp] $Message"
    }
    
    process {
        # Write the message
        Write-Host $MessageWithTimeStamp -ForegroundColor White -BackgroundColor DarkGray
        #Write-Host $Message -ForegroundColor White -BackgroundColor DarkGray
    }
    
    end {
    }
}

### END OF FUNCTION
####################################################################################################

